baseURL: 'https://xmr.gift/'
languageCode: 'en-us'
title: 'xmr.gift: Monero gift cards'
theme: PaperMod

minify:
  minifyOutput: true

params:
  defaultTheme: dark
  disableThemeToggle: true
  socialIcons:
    - name: github
      url: "https://github.com/xmrdotgift"
    - name: matrix
      url: "https://"

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Themes
          url: themes
          weight: 5
        - name: Learn
          url: learn
          weight: 6

    homeInfoParams:
      Title: "Monero gift cards"
      Content: >
        Easy way to give Monero.
